### ISSUE TITLE
建议贵司提升一下reviewer的专业水平

### ISSUE THREAD

**Issue by nyiuang** [scdt-china/interview-assignments#1209]
非常尊崇贵司的工程师文化，code review本身是为了促进交流学习、提升编码水平，进而保证业务质量，但如果将组件设计的作业当作一道面试题的话，建议贵司可以通过内部对齐CR标准，提供最佳实践、组织CR礼仪的workshop等方式，来提升一下reviewer的专业水平，避免让缺乏专业素养，不正面回应问题的同学来随便挂人，这是对每一位候选人的最大尊重。
这是我被review的记录，供参考：https://github.com/scdt-china/interview-assignments/pull/1192

**Comment by baobo5625** [comment]
嗯 收到，我们内部review一下，避免后续问题发生。也多谢建议和反馈。
