### ISSUE TITLE
unable to access XXX,The requested URL returned error: 403

### ISSUE THREAD

**Issue by miaozhiyan** [scdt-china/interview-assignments#819]
remote: Permission to scdt-china/interview-assignments.git denied to {XXXX}.
fatal: unable to access 'https://github.com/scdt-china/interview-assignments.git/': The requested URL returned error: 403

我在push我的分支的时候，提示这个错误，我没有权限操作，应该怎么办呢

**Comment by cfengsequoia** [comment]
> Fork 当前仓库并在相关文件夹下找到你的作业。完成作业后提交一个 Pull Request 即可。

你好，Readme 里有说明，如还有疑问欢迎继续追问。

**Comment by miaozhiyan** [comment]
> 

好的，是我之前操作有问题，现在以及提交了，十分感谢您的回复！

**Comment by miaozhiyan** [comment]
好的，是我之前操作有问题，现在已经提交了，十分感谢您的回复！
